[[theme.fontFaces]]
family="Nunito"
url="https://fonts.gstatic.com/s/nunito/v31/XRXX3I6Li01BKofIMNaDRs7nczIH.woff2"
style="italic"
weight="200 1000"
[[theme.fontFaces]]
family="Nunito"
url="https://fonts.gstatic.com/s/nunito/v31/XRXV3I6Li01BKofINeaBTMnFcQ.woff2"
style="normal"
weight="200 1000"
[[theme.fontFaces]]
family="Space Mono"
url="https://fonts.gstatic.com/s/spacemono/v17/i7dNIFZifjKcF5UAWdDRYERMR3K_MQacbw.woff2"
style="italic"
weight="400"
[[theme.fontFaces]]
family="Space Mono"
url="https://fonts.gstatic.com/s/spacemono/v17/i7dPIFZifjKcF5UAWdDRYEF8RXi4EwQ.woff2"
style="normal"
weight="400"
[[theme.fontFaces]]
family="Space Mono"
url="https://fonts.gstatic.com/s/spacemono/v17/i7dSIFZifjKcF5UAWdDRYERE_FeqHCSRRXaPYw.woff2"
style="italic"
weight="700"
[[theme.fontFaces]]
family="Space Mono"
url="https://fonts.gstatic.com/s/spacemono/v17/i7dMIFZifjKcF5UAWdDRaPpZUFWaHi6WZ3Q.woff2"
style="normal"
weight="700"

[theme]
font="Nunito, sans-serif"
codeFont="'Space Mono', monospace"